### ISSUE TITLE
Multiple machines are showing up as just one

### ISSUE THREAD

**Issue by ebfio** [zweckj/lamarzocco#10]
Hi there, edge case for sure...

I have 2 Lineas (one Mini and one Micra) in 2 different places, each place running their own instance of Home Assistant. In Place 1, the Mini gets discovered just fine and works well with its Home Assistant instance.

On the second place, the second Home Assistant install only detects the Mini again, even though I provided the IP of the Micra. And it tracks how the Mini is, instead of the Micra. 

Help? Tips?

**Comment by zweckj** [comment]
The integration currently supports only one machine, so that would require some changes to the integration.

**Comment by zweckj** [comment]
The 0.12.4 releases will support this https://github.com/zweckj/lamarzocco/releases/tag/v0.12.4-alpha.2

**Comment by ebfio** [comment]
Awesome! Thank you @zweckj. Happy to help test this as well.

**Comment by zweckj** [comment]
Please do! Just be aware that I'm currently developing without a machine to test with, so there might be a lot of issues 😅
