### ISSUE TITLE
Device switch on calls too many entities and causes unexpected behaviours

### ISSUE THREAD

**Issue by TransientWolf** [zweckj/lamarzocco#18]
Beta 5 residual issue having used for a few days and been a bit confused!  Did some testing and digging and discovered:

When you use an automation to call a service to switch the machine on as a DEVICE instead of just turning on the Main On/Off control entity, it also turns on the Auto On/Off control entity and the Steam Boiler enable control entity.  Similarly when you use an automation to call a service to switch off the machine as a DEVICE it turns all three control entities off.

The issue with that is if you have turned the machine off with that automation and then use an entity button or entity automation that specifically calls the Main On/Off control entity, your steam boiler enable remains turned off and doesn't heat up.  Confused the hell out of me!!  Similarly if you turn the machine off manually or by an entity switch, then it leaves the auto on/off enabled and it then starts doing its own thing per the auto schedule.  Given it was Halloween I thought I had a ghost in my machine!!

Obviously can workaround by ensuring any automations call the Main on/off entity but assume you will want to fix if possible so the calling of the DEVICE to turn on by HA links only to the Main on/off entity, not to all three entities that have an on/off function.

Thank you!

**Comment by zweckj** [comment]
should be fixed in beta.6

**Comment by TransientWolf** [comment]
Thanks. Can’t test until tomorrow.

**Comment by TransientWolf** [comment]
Perfect.  They have now moved from controls panel to configuration panel and are not impacted by switching device on or off.  Also noticed the number of drinks (brewings) is not updating - not a problem for me as I don't currently use it, although was thinking of having an automation for cleaning based on every 20 brews.  Not sure if that's because I am not connected via bluetooth.
