### ISSUE TITLE
Prebrew endpoint returning 404 on Mini

### ISSUE THREAD

**Issue by mrvautin** [zweckj/lamarzocco#24]
It seems of late the prebrew endpoint is retuning a 404. Is anyone else getting this? Could they have changed the endpoint?

![image](https://github.com/zweckj/lamarzocco/assets/299398/b4138c00-7245-46e1-89a4-5a1a904878d4)

Edit: I don't have it plumbed so it's prebrew not pre-infusion. It seems the prebrew and preinfusion calls the same endpoint and gets 404.

**Comment by zweckj** [comment]
It's the same `enable-preinfusion` endpoint for preinfusion and prebrew. My app is calling `https://gw-lmz.lamarzocco.io/v1/home/machines/MRxxxxx/setting-preinfusion` which is working fine. Not sure what is happening here.

**Comment by mrvautin** [comment]
Mine seems to be calling `enable-preinfusion`. Not sure why yours is calling `setting-preinfusion` and mine isn't.

**Comment by zweckj** [comment]
Sorry just copied the wrong thing. Mine is also calling `enable-preinfusion` (setting is for the duration)

**Comment by zweckj** [comment]
Found the issue, there's a "." at the end of the URL in the library. No idea how it got there, but will be fixed in a future release

**Comment by zweckj** [comment]
should be fixed since 0.13.1b1
