### ISSUE TITLE
LaMarzocco: After OS Update to 2024.01 no entities available

### ISSUE THREAD

**Issue by areinhar87** [zweckj/lamarzocco#29]
Hi All,

after upgrading to the newest HA OS 2024.01 all entities of my LaMarzocco Mini can't be found anymore. :-(

![Bildschirmfoto 2024-01-04 um 09 58 07](https://github.com/zweckj/lamarzocco/assets/94788039/e91243ce-14b3-45e5-88e0-05246617bb57)

![Bildschirmfoto 2024-01-04 um 09 58 40](https://github.com/zweckj/lamarzocco/assets/94788039/53e36740-6b7e-4a51-8d54-23ab719bbe90)
![Bildschirmfoto 2024-01-04 um 09 59 09](https://github.com/zweckj/lamarzocco/assets/94788039/103eac8b-a80e-461e-b4e2-e01749f56424)

Thank you for your support :-) BR Andy

**Comment by zweckj** [comment]
Install the update of the integration

**Comment by areinhar87** [comment]
you are totally right! :-) thank you it is working!
