### ISSUE TITLE
UNable to get entities: ValueError: Config entry was never loaded! 

### ISSUE THREAD

**Issue by whoisjamesburke110011001100** [zweckj/lamarzocco#32]
Hi 

thank you profusely for creating and maintining this integration

I am experiencing issues  running this integration on a RPI5 with: 

Core
2024.1.0.dev20231218
Supervisor
2024.01.0.dev1902
Operating System
11.3.dev20231212
Frontend
20231218.0.dev

I have installed the integration and configured it, and no entities have appeared (LaMarz.jpg)  ![laMarz](https://github.com/zweckj/lamarzocco/assets/81672470/5305b3c0-e228-482c-8f07-3971a7a08076)
 
I have deleted and reinstalled the integration after rebooting and have not ever seen any entities appear

The log outlines "ValueError: Config entry was never loaded!"  

The integration is "configured successfully" and is "Device is already configured" when trying to re-add the account /machine (LaMarz2.jpg)
![laMarz2](https://github.com/zweckj/lamarzocco/assets/81672470/5051b50e-ceac-4b6a-ab4d-f2900cd108af)

I have attached  a few screenshots and the error log 

Any info would be greatly appreciated. 

[home-assistant_lamarzocco_2024-01-22T06-47-56.648Z.log](https://github.com/zweckj/lamarzocco/files/14006302/home-assistant_lamarzocco_2024-01-22T06-47-56.648Z.log)

**Comment by zweckj** [comment]
Update both the integration and your HA to the latest available versions.
