### ISSUE TITLE
Feature Request: Expose Flush state

### ISSUE THREAD

**Issue by Marcocanc** [zweckj/lamarzocco#38]
It would be great to see whether the machine is currently in backflush mode or not. The LM app seems to be aware of this state (highlighting the button, when it's waiting for paddle movement).
I know it's a very specific request and probably useless to most, but I'm currently building a little companion screen for my Micra using ESPHome and this info would help suppress the shot timer from running when doing a backflush.

Of course I'll be happy to share my ESPHome config with the community once I'm done with it 😊 

Video, if anyone is curious about my project:

https://github.com/zweckj/lamarzocco/assets/1622982/e87f55d4-ea28-48fd-aa65-e999f72a9bf5

**Comment by adampetrovic** [comment]
I've started a similar project in ESPHome, so very keen to see your approach :)

**Comment by zweckj** [comment]
I will be adding this to the core version in the (hopefully) next HA release https://github.com/home-assistant/core/pull/119888

**Comment by Marcocanc** [comment]
Amazing, thanks a lot!

**Comment by Marcocanc** [comment]
> I will be adding this to the core version in the (hopefully) next HA release [home-assistant/core#119888](https://github.com/home-assistant/core/pull/119888)

@zweckj Does this mean that this repo will no longer be updated in the future? If so, it might be worth adding a note in the Readme.

**Comment by Marcocanc** [comment]
@zweckj Unrelated to this PR, but would spare a separate issue. I just upgraded to the core version (from 0.13.2 HACS) and noticed that there's now a significant delay on the on/off switch, mostly in terms of state, not in executing the command. Usually more than 5 seconds. Is this a known problem? Previously this was <1s for me.

**Comment by zweckj** [comment]
That should not be. The core version has however problems with the latest gateway firmware versions, and this will only be fixed in 2024.07

**Comment by Marcocanc** [comment]
@zweckj Could these issues be related?
I will downgrade to the non-core version for now, hoping that the 2024.07 fix will address the latency as well 🤞🏻 
I also noticed that the steam boiler target temp is gone. I'm assuming it's because the steam levels abstract it away. Unfortunately this takes away the ability to see if the steam target temp has been reached, would be nice to have it back as a sensor value at some point.
