### ISSUE TITLE
Deactivation of the WebSocket

### ISSUE THREAD

**Issue by ctschumi** [zweckj/lamarzocco#40]
Hello
I installed the Integration a few months ago. Since then i am not able to connect to the machine via wlan with the LaMarzocco App. Only Bluetooth connection available. I'm not even sure if the Integration is connected via Wlan.. I allready tried to reset the connection with the app a few Times.
Do you know how to fix the problem?
Thanks and Regards

**Comment by zweckj** [comment]
Can you share debug logs and diagnostic data from the integration?
