### ISSUE TITLE
How can I pass the "number" entity to homekit?

### ISSUE THREAD

**Issue by alegend2k** [zweckj/lamarzocco#41]
Hello there,
can anyone tell me how to expose the number entity (for coffee temperature) to homekit.
e.g like a heating thermostat? Is this possible or not?

**Comment by zweckj** [comment]
Hi, this is not possible at the moment.

**Comment by alegend2k** [comment]
I manage it by using a climate sensor which allows me to treat it as a heater....so it works.
If i turn heating of machine turns off....
