### ISSUE TITLE
Shot timer and active brew did not work

### ISSUE THREAD

**Issue by forchi89** [zweckj/lamarzocco#43]
Hello, I had a problem that the shot timer and brew active didn't work anymore (worked very well before), now everything is working again thanks to ChatGPT... I had a small summary output... 
 Can anyone tell me what I did wrong? 

For additional info, HA runs in a VM in Unraid (HAOS 13.2)

And here is the summary from ChatGPT:
Issue: I ran into an error with the websockets library in Home Assistant. The installed version websockets==14.1 caused conflicts with several other dependencies, such as lmcloud, which required a newer version of websockets. 

The error message was:
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
Several other packages also required a version of websockets that was newer than 14.1.

Solution: To resolve the issue, I downgraded websockets to version 11.0.2, which is compatible with all the required packages.

I installed websockets 11.0.2 using:
python -m pip install websockets>=11.0.2

Restarted Home Assistant to apply the changes.
Conclusion: The downgrade to websockets 11.0.2 fixed the conflicts, and Home Assistant is now working without issues.

thank you
Tobi

**Comment by zweckj** [comment]
@forchi89 this repo is not really being maintained any longer. The integration is part of Home Assistant core for a while now. Please uninstall the custom integration and use the core one.
