### ISSUE TITLE
cannot install on current stable HomeAssistant version

### ISSUE THREAD

**Issue by neuralldev** [zweckj/lamarzocco#6]
Hi, I tried to install your fork on HA, current stable docker version is Home Assistant 2023.3.5.

When I launch the integration it fails to load the service with this error message in the logs:

```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 09:29:53 (3 occurrences)
Last logged: 09:30:01

Unable to install package lmcloud==0.3.35: ERROR: Cannot install lmcloud==0.3.35 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

```

There is no minimum HA version defined in your setup procedure so I assume the current stable docker version is not ok. What can I do as I cannot modify docker image?

**Comment by zweckj** [comment]
You need a HA newer than 2023.8.0
