### ISSUE TITLE
Steam and coffee temp sensors no longer working

### ISSUE THREAD

**Issue by PierreBergamin** [zweckj/lamarzocco#7]
It seems that the steam and coffee temp sensors stopped working for my Linea Micra. Using latest. Is it a known issue?

**Comment by zweckj** [comment]
I haven't heard any other complaints thus far. My IoT board is still broken, so unfortunately I can't do testing on my end currently.

**Comment by luuuis** [comment]
Sensors are working well for me on 2023.8.3.

**Comment by neuralldev** [comment]
works for me as well on 2023.10.3 with actual LM 2.12 firmware
